import React from "react";

function Hero() {
  return (
    <div>
      <h1 className="font-extrabold text-[#222328] text-[32px] ">
        Community Showcase
      </h1>
      <p className="mt-2 text-[#666e75] text-[14px] max-w-[500px]">
        Browse through a collection of imaginative and visually stunning images
        generated by DALL-E AI
      </p>
    </div>
  );
}

export default Hero;
